# Generated by Django 3.1.2 on 2020-10-19 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_purchase_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='product',
            new_name='products',
        ),
    ]
